- name: Install pip
  ansible.builtin.dnf:
    name: python3-pip
    state: present
  tags:
    - install

- name: Install virtualenv
  ansible.builtin.pip:
    name: virtualenv
    state: present
  tags:
    - install

- name: create test_app directory
  ansible.builtin.file:
    path: "{{ app_directory }}"
    state: directory
  tags:
    - install

- name: Copy app.py
  ansible.builtin.copy:
    src: ../test_app/app.py
    dest: "{{ app_directory }}/app.py"
  tags:
    - install
    - reload
    - reload_requirements
  notify:
    - Restart test_app

- name: Copy requirements.txt
  ansible.builtin.copy:
    src: ../test_app/requirements.txt
    dest: "{{ app_directory }}/requirements.txt"
  tags:
    - install
    - reload_requirements
  notify:
    - Restart test_app

- name: Create virtualenv
  ansible.builtin.pip:
    virtualenv: "{{ app_directory }}/venv"
    virtualenv_python: python3
    requirements: "{{ app_directory }}/requirements.txt"
  tags:
    - install
    - reload_requirements

- name: Template systemd service file
  ansible.builtin.template:
    src: test_app.service.j2
    dest: /etc/systemd/system/test_app.service
  notify:
    - Daemon reload
    - Restart test_app
  tags:
    - install
    - reload
    - reload_requirements
    - template

- name: Systemd test_app service
  ansible.builtin.systemd_service:
    daemon_reload: yes
    name: test_app
    state: started
    enabled: yes
  tags:
    - install
    - reload
    - reload_requirements
